name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - mkdocs/**
      - mkdocs.yml
    tags-ignore:
      - "**"

permissions:
  contents: write

jobs:
  deploy-dev:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          lfs: true

      - uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --only-group docs

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy dev docs
        run: uv run mike deploy --push --update-aliases dev

