name: Unit Tests

on:
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    uses: ./.github/workflows/xcode-build.yml
    with:
      operation: test
    permissions:
      contents: read
